### ISSUE TITLE
Update link on website for beta signup

### ISSUE THREAD

**Issue by alexselig** [nosidewen/support#19]
@beardedbadger Let's update the web sign up on both sites to be: 
First Name
Last Name
City
Email
LinkedIn URL (make sure there's no http: in the box)

**Comment by beardedbadger** [comment]
@alexselig  Two considerations here.

## Google Forms
Not the prettiest form and probably not the first impression I'd prefer to give.  IMO, the squarespace capture is currently better than the Google form. What's our other options here?  

An alternative that I've recently followed through can be seen by visiting.  https://superhuman.com/  IMO there's some really good things to learn from what they are doing. 

## Length of Lead Form

In general we want to have the shortest sufficient form here because capturing the email is probably most important.  I worry that the current form ask more information than necessary and worry that it will reduce conversion at this first step where volume is most critical. 

## Some Ways to Move forward. 

1. If the primary reason for this ask is to consolidate flows, let's look at how we can do that...I know that I can send the Squarespace form to any google spreadsheet, we just need to have the column names match. 

2. Let's remap all the possible flows and create a single **NEW** capture method that addresses the UX goals and consolidates the funnel for ease of managing.  Agree that we want them to flow into a single funnel for ease of automation.

**Comment by alexselig** [comment]
@beardedbadger Made automation here. Updated the task above
